name: Webpage

on:
  push:
    branches:
      - main
    paths:
      - "install.cfg"

jobs:
  webpage:
    runs-on: ubuntu-latest
    name: Compile Webpage
    steps:
      - name: Compile Webpage
        uses: instructions-d-installation/web-installation-instruction-action@0.1.0
      - name: Deploy Webpage
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          